# Generated by Django 3.2.8 on 2021-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vip',
            field=models.BooleanField(default=True),
        ),
    ]
