# Generated by Django 3.2.8 on 2021-10-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_pcs', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('vip', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.shop')),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
    ]
