# Generated by Django 3.2.8 on 2021-10-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
