# Generated by Django 3.2.8 on 2021-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SHOP',
            },
        ),
    ]
