# Generated by Django 3.2.8 on 2021-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
